### ISSUE TITLE
Добавить поиск в "метрику"

### ISSUE THREAD

**Issue by tseglevskiy** [LizaAlert-HotLine/AndroidMobileWorkplace#63]
Нужно: 

1. Добавить onResumeActivity/onPauseActivity в активити поиска

2. При поиске отправить событие Search и передать в нем значение строки

3. При выборе региона отправить событие Region и передать название региона

Для передачи события использовать метод
YandexMetrica.reportEvent(String eventName, Map<String, Object> attributes)

**Comment by tseglevskiy** [comment]
https://tech.yandex.ru/metrica-mobile-sdk/doc/mobile-sdk-dg/concepts/android-methods-docpage/

**Comment by tseglevskiy** [comment]
Еще просьба. Строки с идентификаторами событий сделать константами и поселить в класс
CoreLib/src/main/java/ru/lizaalert/hotline/lib/YM.java

**Comment by ivandigital** [comment]
Как посмотреть результат трекинга событий в Яндекс-Метрике?

**Comment by tseglevskiy** [comment]
1. Я не могу найти в интерфейсе метрики возможность открыть статистику. Вроде была, а сейчас не вижу. Проще всего зарегистрировать в метрике свое приложение и на время отладки прописать его id в файле LAApp/src/debug/res/values/strings.xml

2. Добавь, пожалуйста, к инициализации метрики еще и YandexMetrica.setDispatchPeriod(2); (в MyApp.onCreate)

**Comment by ivandigital** [comment]
Готово

**Comment by tseglevskiy** [comment]
Кууул!
Пожалуйста, в новый файл добавь заголовок с лицензией, и укажи свои имя и
адрес в этом заголовке и файле AUTHORS.

**Comment by ivandigital** [comment]
Готово.
Это все добавилось к тому же пул-реквесту.

2015-01-24 0:37 GMT+03:00 Igor Tseglevskiy <notifications@github.com>:

**Comment by tseglevskiy** [comment]
Закоммитил. Спасибо!

**Comment by tseglevskiy** [comment]
Ты с Google Drive и Google Spreadsheet API работал?

**Comment by ivandigital** [comment]
Что нужно сделать?
№ тикета?

2015-01-24 8:25 GMT+03:00 Igor Tseglevskiy <notifications@github.com>:

> Ты с Google Drive и Google Spreadsheet API работал?
>
>
> On Sat, Jan 24, 2015 at 1:41 AM, Igor Tseglevskiy <
