### ISSUE TITLE
Добавление строки в Google Spreadsheet

### ISSUE THREAD

**Issue by tseglevskiy** [LizaAlert-HotLine/AndroidMobileWorkplace#66]
Необходимо сделать модуль для добавления строки в Google Spreadsheet. 

Таблица будет с явным указанием имеющих к ней доступ. Поэтому нужно будет реализовать авторизацию. Требований к авторизации нет (или об основной гугловый аккаунт на девайсе, или сохраняя логин/пароль в настройках, или как угодно еще).

**Comment by tseglevskiy** [comment]
Вдруг будет полезно:
https://github.com/fernandezpablo85/scribe-java
https://github.com/claytantor/marketplace-helloworld-spring3

**Comment by ivandigital** [comment]
Нужен пример таблицы со структурой данных в ней.
24 янв. 2015 г. 20:44 пользователь "Igor Tseglevskiy" <
notifications@github.com> написал:

**Comment by tseglevskiy** [comment]
Задачу надо решить в общем виде. Варианта два, можно выбрать любой: 
- на вход метода передается список строк, и они попадут в соответствующие столбцы таблицы (по порядку)
- у таблицы  в первой строчке перечислены ID столбцов, а на вход метода передается hashmap.

**Comment by ivandigital** [comment]
Игорь, задача интересная и я смогу ее сделать.
Но у меня не так много времени, которое я могу уделять этому проекту.
Насколько срочна эта задача?
И сколько времени есть на ее реализацию?


2015-01-25 17:15 GMT+03:00 Igor Tseglevskiy <notifications@github.com>:

**Comment by tseglevskiy** [comment]
Мы тут все можем уделять проекту очень немного времени. Он изначально волонтерский, и это определяет среднюю скорость разработки. По имеющемуся опыту неделя-две на задачу -- это нормальная скорость. 

Если ты боишься, что времени это может занять больше, или что у тебя не хватит сил одному сделать эту задачу, то я бы тебя попросил тогда провести аналитику, описать ход решения и помочь разбить эту задачу на несколько маленьких.

**Comment by ivandigital** [comment]
Это должен быть отдельный модуль? Или в составе CoreLib?

**Comment by tseglevskiy** [comment]
Все экспериментальное родится сначала в SandboxApp.

**Comment by tseglevskiy** [comment]
http://www.blogface.org/2013/07/reading-google-spreadsheets-from.html
http://stackoverflow.com/questions/12478582/how-to-connect-android-app-with-google-spreadsheet

**Comment by tseglevskiy** [comment]
Прототип работает.
